### ISSUE TITLE
Feature Request: display by period instead of by node, with node IDs and uptime

### ISSUE THREAD

**Issue by mik-tf** [threefoldfoundation/peppermint#1]
# Feature Request

- display by period instead of by node, with node IDs and uptime
  - e.g. by farm --> by period --> by node (optional)

**Comment by scottyeager** [comment]
I've implemented this feature. It's working locally but there's some issue with http/https when I try to deploy. Investigating.

**Comment by scottyeager** [comment]
This is complete.
