### ISSUE TITLE
Error when fetching farm with node created within the current minting period

### ISSUE THREAD

**Issue by mik-tf** [threefoldfoundation/peppermint#10]
# Situation

- we get: Error when fetching farm with node created within the current minting period
- e.g. farm 197
- As shown by Scott, the alpha minting can't fetch 7285
![image](https://github.com/user-attachments/assets/f3105a49-946d-4d00-a140-4a0ffe154547)
- UI-UX:
![image](https://github.com/user-attachments/assets/80e22cc2-0165-4a69-9682-84683aabca91)

**Comment by scottyeager** [comment]
Fix was deployed and it looks okay. Here's an example with a node created during the current period:

![image](https://github.com/user-attachments/assets/a0d286c0-6624-4ffd-85af-cd695db67f7f)
